
'use client'

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BgNoise from "@/components/BgNoise";
import Footer from "@/components/Footer";
import { Navbar } from "@/components/Navbar";
import NewsletterCTA from "@/components/NewsletterCTA";
import AOS from 'aos';
import 'aos/dist/aos.css'; 
import { useEffect } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Aimgeneration",
//   description: "Generated by IhjasDev",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  useEffect(() => {
    AOS.init({
      duration: 1000, // Animation duration in milliseconds
      once: true, 
      // Whether animation should happen only once
    });
  }, []);

  return (
    <html lang="en">
  <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
    <BgNoise />
    <div className="flex min-h-screen flex-col">
      <Navbar />
      <main className="flex-1">{children}</main>
      <NewsletterCTA />
      <Footer />
      
    </div>
  </body>
</html>

  );
}
